### ISSUE TITLE
Errors in section 4.x Please remove

### ISSUE THREAD

**Issue by GeekyShiva** [GeekyShiva/FordMotors-SelfDrivingCar#30]
@falcon1996 
@StrawHatDragon100 @tanmay-e-patil  Please review your commits/sections as I am still finding logical errors like "machine learning model" in the document SRS.md

If you have some issues changing the things then I request please consult me and do the needful asap

**Comment by StrawHatDrag0n** [comment]
Resolved

**Comment by GeekyShiva** [comment]
@falcon1996 @StrawHatDragon100 @tanmay-e-patil  Issues resolved with latest merged PR
